blank_issues_enabled: false
contact_links:
  - name: Contributing guidelines
    url: https://github.com/Serpentiel/arikawa-boilerplate/blob/main/CONTRIBUTING.md
    about: Don't forget to check our contributing guidelines out!
