# logger defines the parameters for the logger.
logger:
  # path is the path to the log file.
  path: go-cli.log

  # retain defines the parameters for log file retention.
  retain:
    # days is the number of days to retain log files.
    days: 30

    # copies is the number of log files to retain.
    copies: 3
